### ISSUE TITLE
List the most frequent articles on the landing page

### ISSUE THREAD

**Issue by sbastn** [dnsimple/dnsimple-support#100]
It could be interesting to give a shortcut to the most viewed articles on the landing.

Here is the top 10 since 2015. Ignore the `/` link
<img width="381" alt="screen shot 2015-10-08 at 4 19 33 pm" src="https://cloud.githubusercontent.com/assets/80610/10369028/66175064-6dd8-11e5-8e0b-e5942ecab132.png">

Does this make sense?

**Comment by weppos** [comment]
@sbastn most viewed pages are not necessary the most relevants for our customers. In some cases, these pages have an high number of views because they are linked somewhere else or have good ranking on the search engines.

I'd not use the page view as the only param. However, we can consider to link in home page the most common questions.

**Comment by sbastn** [comment]
Totally going for more relevant pages. If someone knows the best way to dig them up, *cough* @meeunier  *cough*, that would be useful.

**Comment by weppos** [comment]
Most frequent questions from customer support is probably one good way to start.

**Comment by meeunier** [comment]
![cough](https://media2.giphy.com/media/yoJC2xBNWULqliMcwg/200.gif)

**Comment by weppos** [comment]
Closing for now. Should we decide there is a reason to work on this again, we can reopen.
