### ISSUE TITLE
Article about 1 click services

### ISSUE THREAD

**Issue by jacegu** [dnsimple/dnsimple-support#196]
How to find them, apply them to a domain and un-apply them.
It may also be helpful to add a section about contributing with new ones.

**Comment by weppos** [comment]
@jacegu FYI https://support.dnsimple.com/articles/services/ and https://support.dnsimple.com/articles/contributing-services/

**Comment by jacegu** [comment]
Then what we have to do is to change some text here and there so these articles show up when you search for _1 click service_ (that's what made me open this ticket):

<img width="579" alt="screen shot 2016-08-25 at 19 03 52" src="https://cloud.githubusercontent.com/assets/381143/17978487/af9a2d26-6af6-11e6-9ff0-ce607f39c27e.png">

**Comment by weppos** [comment]
It's tricky, as for example someone may also search for `one-click service`, or `one click service`. I'm not sure how the search is indexed, hence I wonder if we can add the meta tag keywords (even if ignored by search engines, it may be used by us).

Otherwise, another option is to add the various variants in some way in the article such as:

> One click services (or 1-click services) are ...

Also note that the screenshots seems to use _one click service_ (hence we may definitely want at least to change the title and/or the Adding and Removing to use _one click service_.

**Comment by weppos** [comment]
I renamed services to "One-click service". If we want more variants, we likely have to place that inline in the text.
