### ISSUE TITLE
Update DNSSEC support article

### ISSUE THREAD

**Issue by aeden** [dnsimple/dnsimple-support#261]

**Comment by weppos** [comment]
It should also be renamed from /articles/dnssec-support/ to /articles/dnssec/ with a redirect.

**Comment by aeden** [comment]
I was going to have two articles: one that is this one which is an overview of our support, and another that explains how to manage DNSSEC (i.e. enable and disable).

**Comment by aeden** [comment]
Does it make more sense to combine these two things into a single article?

**Comment by aeden** [comment]
I think I'll just have the one article as you suggest.

**Comment by weppos** [comment]
It really depends on the length. I've been merging most of articles into a single topic

e.g.
https://support.dnsimple.com/articles/dns-hosting/
https://support.dnsimple.com/articles/whois-privacy/ https://support.dnsimple.com/articles/secondary-dns/
https://support.dnsimple.com/articles/ssl-certificates/
https://support.dnsimple.com/articles/email-forwarding/

because it's nice and easy to have a single entry point.

Nothing prevents us to add extra articles that explains a specific element, or detail some specific areas.

**Comment by aeden** [comment]
Implemented.
