### ISSUE TITLE
Ruby Sass is deprecated

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-support#362]
```
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811
```

**Comment by sbastn** [comment]
Nanoc does not yet support Sassc: nanoc/nanoc#1343. It's currently a feature request: https://github.com/nanoc/features/issues/45

**Comment by kayla-broussard** [comment]
@sbastn @weppos while this does not resolve the issue (and is not a nanoc official solution), it appears as though someone has created a filter to assist with this since this issue was created: 

https://gist.github.com/jarrodldavis/72d450c636ffed67a0a8a3c31d261387

Nanoc themselves do not appear to be working on this. :/
