### ISSUE TITLE
Change Transfer Out page wording to be more clear that our upstream provider releases the domain

### ISSUE THREAD

**Issue by kayla-broussard** [dnsimple/dnsimple-support#549]
The current support page for transferring a domain away from DNSimple makes it sound like we're the one to release the domain, which isn't really the case. 

The article should be updated to make it more clear that the upstream provider is the one releasing the domain, and that we have zero control over when this transfer completes.

**Comment by weppos** [comment]
One thing we need to refrain to is to reference the "transfer away" something that triggers the transfer. In fact, in the API we shifted the description to "prepare for transfer" or "authorize transfer out" which really means: we unlock the domain, sent the auth code, but no transfer is initiate (as it must be initiated at the gaining registrar).

Regarding the transfer process, whether it's us or the upstream provider releasing the domain in most cases this is not very relevant to the customer as the outcome is that they will still have to wait for it to be completed. Perhaps we can make it more clear so that in general it requires up to 6 days for the transfer to complete as per ICANN transfer or similar rules (it is 5, but often customers don't realize that if they start it at 10pm on the 2nd and they check at 4am on the 7th, it's not 5 days yet. Also, it's not as precise, so let's use some buffer) and we currently have no way to speed up the process.

**Comment by kayla-broussard** [comment]
@weppos transfer away doesn’t appear in the document, other than the URL - are you suggesting this be changed as well?

My suggested edit that I was going to make a PR with was this:

> After the transfer at the new registrar is initiated and the transfer code is provided, the transfer will be initiated at the Registry level. The Registry has 5 - 7 business days to release your domain(s) as per ICANN Transfer policy. The transfer will automatically be approved at the end of this period. There's no way to speed this process along. 
> 
> Once the transfer is approved, the domain(s) will now be with your new registrar, and no longer with DNSimple.


Does that suit what you're suggesting? :)

**Comment by kayla-broussard** [comment]
@weppos Sure! Specifically just this article: https://support.dnsimple.com/articles/transferring-domain-away/

**Comment by weppos** [comment]
It works. Just keep in mind it's not the registry to release them, it's the registrar.
