### ISSUE TITLE
Clarify that Professional or higher plan is necessary to customize invoice details

### ISSUE THREAD

**Issue by deandre** [dnsimple/dnsimple-support#695]
Running into a bit of a back and forth with a customer on a Personal plan who wants to customize the details that are included on their invoices.

I've explained that to do this, it's necessary to customize the billing email first, which is a feature available on higher tiers. Our documention/FAQ is confusing in this respect:

> In the FAQ it says that billing information can be changed by contacting support (https://support.dnsimple.com/articles/billing-settings/#customize-billing-information) - see screenshot. If there is no such option,I find it confusing not knowing that beforehand as I need these informations on the invoice in order to have them registered in accounting.

Raising this issue to make this more apparent in the info tip.

Groove ticket: https://dnsimple.groovehq.com/tickets/103224

**Comment by jacegu** [comment]
@deandre I actually had to go back to the app to verify the behaviour we have because I couldn't tell from the top of my head. 

Here is how it works today:
- The only thing that is tied to being subscribed to a specific plan to be able to modify is the _custom billing email_. (The logic behind this is that on a Personal plan it makes little sense to have the invoices sent to a different person/department, which is the purpose of this setting.)
-  You should be able to modify the billing information (that is, tax ID, company name and address) on your invoices on any plan.
- Contacting support is only relevant if an invoice was recently generated and the customer realizes that some billing information has to be added and/or modified on it.

Maybe having both things on the same section in the UI can be a little bit confusing? /cc @sbastn
